version: 2
jobs:
  build:
    docker:
      - image: python:3
      - image: gcc:8.1.0
      
    steps:
      - checkout
      - run:
          command: pip install numpy
      - run: 
          command: python -m unittest
          
      - run: gcc -o HelloWorld HelloWorld.c
      
      - run: 
          command: pwd
          
      - store_artifacts:
          PATH: ./
          destination: artifact-file

