version: 2
jobs:
  build:
    docker:
      - image: python:3
      - image: gcc:8.1.0
      
    steps:
      - checkout
      - run:
          command: pip install numpy
      - run: 
          command: python -m unittest
          
      - run: gcc -o HelloWorld HelloWorld.c
      - run: ls
      - run:
          command: mkdir artifacts ; mv HelloWorld artifacts/
          
      - add_ssh_keys:
          fingerprints:
            - "2c:e5:c9:5c:10:c1:bc:88:de:08:43:65:08:c6:46:5e"

      - run: sh ./deploy.sh
      
      - store_artifacts:
          PATH: ./artifacts
          destination: artifact-file

