version: 2
jobs:
  build:
    docker:
      - image: python:3

    steps:
      - checkout
      - run:
          command: pip install numpy
      - run: 
          command: python -m unittest
    build:
     docker:
      - image: gcc:8.1.0
      
     steps:
      - checkout
      - run: gcc dump HelloWorld.c
      
      - store_artifacts:
          path: /artifact/CCode
          destination: artifact-file
